[package]
name = "tai_first_proj"
version = "0.1.0"
edition = "2021"

[lib]
name = "tai_first_project"
path = "src/lib.rs"

[dependencies]
argparse = "0.2.2"
plotters = "0.3.7"
rand = "0.9.0"
serde = { version="1.0", features = ["derive"]}
serde_json = "1.0.139"
